
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"; // .env file 읽어와
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts", // seed.ts 제작 후 삽입 : 신식 방법
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
